"""initial star schema

Revision ID: 871a493d0d3e
Revises: 
Create Date: 2026-07-30 23:14:28.659146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '871a493d0d3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Native enum types created implicitly by the sa.Enum columns below. Alembic's
# autogenerate emits CREATE TYPE on first use but never emits a matching DROP, so
# without the explicit cleanup at the end of downgrade() these survive the
# migration and the next upgrade fails with:
#   psycopg.errors.DuplicateObject: type "channel_type" already exists
# Phase 2 drops and regenerates this database repeatedly, so a one-way migration
# would be an obstacle, not a theoretical concern. Verified by round-tripping.
ENUM_TYPE_NAMES: tuple[str, ...] = (
    'absence_type',
    'application_stage',
    'channel_type',
    'event_type',
    'goal_status',
    'output_type',
    'requisition_status',
    'risk_band',
    'sentiment',
    'termination_type',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_date',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False, comment='1-4'),
    sa.Column('month', sa.SmallInteger(), nullable=False, comment='1-12'),
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('month_end', sa.Date(), nullable=False),
    sa.Column('quarter_start', sa.Date(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False, comment='Monday'),
    sa.Column('iso_week', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False, comment='1=Mon, 7=Sun'),
    sa.Column('is_workday', sa.Boolean(), nullable=False, comment='Mon-Fri and not a holiday. Denominator for absenteeism.'),
    sa.Column('is_month_end', sa.Boolean(), nullable=False),
    sa.Column('tenure_day_index', sa.Integer(), nullable=False, comment='Days since the start of the spine; eases date maths.'),
    sa.PrimaryKeyConstraint('day'),
    comment='One row per calendar day across the 36-month window.'
    )
    op.create_index('ix_dim_date_month_start', 'dim_date', ['month_start'], unique=False)
    op.create_index('ix_dim_date_quarter_start', 'dim_date', ['quarter_start'], unique=False)
    op.create_index('ix_dim_date_week_start', 'dim_date', ['week_start'], unique=False)
    op.create_table('dim_department',
    sa.Column('department_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False, comment='Billable departments file timesheets; utilization applies only to these.'),
    sa.Column('carries_revenue', sa.Boolean(), nullable=False, comment='Whether revenue per FTE is meaningful for this dept.'),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('code'),
    comment="8 departments. Also serves as the 'team' grain for productivity metrics."
    )
    op.create_table('dim_job_level',
    sa.Column('job_level_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False, comment='L1..L6'),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False, comment='1 = most junior; orders levels for span of control.'),
    sa.Column('comp_band_min', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comp_band_max', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_manager_level', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('job_level_id'),
    sa.UniqueConstraint('code'),
    comment="6 job levels. The comp band is here so the flight-risk component 'comp percentile vs band' needs no separate compensation table."
    )
    op.create_table('dim_location',
    sa.Column('location_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('code'),
    comment='4 locations.'
    )
    op.create_table('dim_source',
    sa.Column('source_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('channel_type', sa.Enum('referral', 'agency', 'job_board', 'inbound', 'campus', 'internal', name='channel_type'), nullable=False),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('code'),
    comment='Hiring channels. The sourcing-decay scenario contrasts agency with referral.'
    )
    op.create_table('dim_survey',
    sa.Column('survey_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False, comment='Q1-Y1'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('quarter_start', sa.Date(), nullable=False),
    sa.Column('opens_on', sa.Date(), nullable=False),
    sa.Column('closes_on', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('survey_id'),
    sa.UniqueConstraint('code'),
    comment='6 quarterly engagement surveys at ~70% participation.'
    )
    op.create_table('dim_employee',
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('display_name', sa.String(length=96), nullable=False),
    sa.Column('manager_id', sa.String(length=12), nullable=True, comment='Self-reference. NULL for the top of the org.'),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True, comment='NULL means currently active.'),
    sa.Column('termination_type', sa.Enum('voluntary', 'involuntary', name='termination_type'), nullable=True, comment='Set if and only if termination_date is set.'),
    sa.Column('termination_reason', sa.String(length=64), nullable=True),
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('job_level_id', sa.SmallInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=True, comment='Channel this person was hired through. Drives source effectiveness, quality of hire, and cohort retention by source. NULL for founding staff.'),
    sa.Column('comp_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fte', sa.Numeric(precision=4, scale=3), nullable=False, comment='1.000 = full time. Denominator for revenue per FTE.'),
    sa.ForeignKeyConstraint(['department_id'], ['dim_department.department_id'], ),
    sa.ForeignKeyConstraint(['job_level_id'], ['dim_job_level.job_level_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['dim_location.location_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['dim_employee.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['dim_source.source_id'], ),
    sa.PrimaryKeyConstraint('employee_id'),
    comment='~1,850 employee records over 36 months. Type-1: current state only. History is in fact_employment_event; as-of-month state is in the monthly headcount snapshot.'
    )
    op.create_index('ix_dim_employee_department', 'dim_employee', ['department_id'], unique=False)
    op.create_index('ix_dim_employee_hire_date', 'dim_employee', ['hire_date'], unique=False)
    op.create_index('ix_dim_employee_manager', 'dim_employee', ['manager_id'], unique=False)
    op.create_index('ix_dim_employee_termination_date', 'dim_employee', ['termination_date'], unique=False)
    op.create_table('fact_department_revenue',
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.Column('quarter_start', sa.Date(), nullable=False),
    sa.Column('revenue_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['dim_department.department_id'], ),
    sa.PrimaryKeyConstraint('department_id', 'quarter_start'),
    comment='Revenue by department by quarter. Added because Revenue per FTE is in METRICS.md but had no source table in the phase-1 fact list.'
    )
    op.create_table('dim_requisition',
    sa.Column('requisition_id', sa.String(length=12), nullable=False, comment='R-0001'),
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('job_level_id', sa.SmallInteger(), nullable=False),
    sa.Column('hiring_manager_id', sa.String(length=12), nullable=True),
    sa.Column('status', sa.Enum('open', 'filled', 'cancelled', 'on_hold', name='requisition_status'), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False, comment='Start of the time-to-fill clock.'),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('target_start_date', sa.Date(), nullable=True),
    sa.Column('openings', sa.SmallInteger(), nullable=False),
    sa.Column('internal_cost', sa.Numeric(precision=12, scale=2), nullable=False, comment='Recruiter time, referral bonus, tooling.'),
    sa.Column('external_cost', sa.Numeric(precision=12, scale=2), nullable=False, comment='Agency fees, job board spend, advertising.'),
    sa.ForeignKeyConstraint(['department_id'], ['dim_department.department_id'], ),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['dim_employee.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_level_id'], ['dim_job_level.job_level_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['dim_location.location_id'], ),
    sa.PrimaryKeyConstraint('requisition_id'),
    comment='410 requisitions. Costs live here because cost per hire is (internal_cost + external_cost) / hires_in_period at req grain.'
    )
    op.create_index('ix_dim_requisition_department', 'dim_requisition', ['department_id'], unique=False)
    op.create_index('ix_dim_requisition_status_opened', 'dim_requisition', ['status', 'opened_date'], unique=False)
    op.create_table('fact_absence',
    sa.Column('absence_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('absence_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=4, scale=2), nullable=False, comment='Supports half days.'),
    sa.Column('absence_type', sa.Enum('unplanned', 'sick', 'pto', 'leave', name='absence_type'), nullable=False),
    sa.Column('is_unplanned', sa.Boolean(), nullable=False, comment='Denormalized from absence_type so the absenteeism numerator is one predicate.'),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('absence_id'),
    comment='One row per absence occurrence. Only unplanned/sick count as absenteeism.'
    )
    op.create_index('ix_fact_absence_employee_date', 'fact_absence', ['employee_id', 'absence_date'], unique=False)
    op.create_table('fact_employment_event',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.Enum('hire', 'promotion', 'lateral_transfer', 'manager_change', 'comp_change', 'termination', name='event_type'), nullable=False),
    sa.Column('from_department_id', sa.SmallInteger(), nullable=True),
    sa.Column('to_department_id', sa.SmallInteger(), nullable=True),
    sa.Column('from_job_level_id', sa.SmallInteger(), nullable=True),
    sa.Column('to_job_level_id', sa.SmallInteger(), nullable=True),
    sa.Column('from_manager_id', sa.String(length=12), nullable=True),
    sa.Column('to_manager_id', sa.String(length=12), nullable=True),
    sa.Column('from_comp_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('to_comp_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('termination_type', sa.Enum('voluntary', 'involuntary', name='termination_type'), nullable=True, comment='Set only on TERMINATION events.'),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_department_id'], ['dim_department.department_id'], ),
    sa.ForeignKeyConstraint(['from_job_level_id'], ['dim_job_level.job_level_id'], ),
    sa.ForeignKeyConstraint(['from_manager_id'], ['dim_employee.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_department_id'], ['dim_department.department_id'], ),
    sa.ForeignKeyConstraint(['to_job_level_id'], ['dim_job_level.job_level_id'], ),
    sa.ForeignKeyConstraint(['to_manager_id'], ['dim_employee.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id'),
    comment="Every transition in an employee's record. from_*/to_* columns make promotions distinguishable from lateral transfers, which is what internal mobility rate requires."
    )
    op.create_index('ix_fact_employment_event_employee_date', 'fact_employment_event', ['employee_id', 'event_date'], unique=False)
    op.create_index('ix_fact_employment_event_type_date', 'fact_employment_event', ['event_type', 'event_date'], unique=False)
    op.create_table('fact_flight_risk_score',
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('as_of_month', sa.Date(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False, comment='0-100'),
    sa.Column('band', sa.Enum('low', 'moderate', 'elevated', 'high', name='risk_band'), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Per-factor value, weight, and contribution. Drives the expandable reason table.'),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'as_of_month'),
    comment='Computed in phase 3 by a transparent weighted score, not a model. `components` holds each contributing factor and its weight so the score can be explained per employee in the demo.'
    )
    op.create_index('ix_flight_risk_month_score', 'fact_flight_risk_score', ['as_of_month', 'score'], unique=False)
    op.create_table('fact_goal',
    sa.Column('goal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.Column('quarter_start', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False, comment='Must be non-zero; the metric guards division.'),
    sa.Column('actual_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('on_track', 'at_risk', 'complete', 'missed', name='goal_status'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['dim_department.department_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id'),
    comment='~2,400 goals. Attainment is AVG(actual / target) capped at 1.5 — the cap is applied in the metric layer, not stored.'
    )
    op.create_index('ix_fact_goal_department_quarter', 'fact_goal', ['department_id', 'quarter_start'], unique=False)
    op.create_index('ix_fact_goal_employee_quarter', 'fact_goal', ['employee_id', 'quarter_start'], unique=False)
    op.create_table('fact_monthly_headcount_snapshot',
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('job_level_id', sa.SmallInteger(), nullable=False),
    sa.Column('manager_id', sa.String(length=12), nullable=True),
    sa.Column('comp_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fte', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('tenure_months', sa.SmallInteger(), nullable=False, comment='Whole months from hire_date to this month_start.'),
    sa.Column('active_at_month_start', sa.Boolean(), nullable=False),
    sa.Column('active_at_month_end', sa.Boolean(), nullable=False),
    sa.Column('terminated_in_month', sa.Boolean(), nullable=False, comment='Numerator flag for attrition. Denominator is average of the two active flags.'),
    sa.Column('hired_in_month', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['dim_department.department_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_level_id'], ['dim_job_level.job_level_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['dim_location.location_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['dim_employee.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('month_start', 'employee_id'),
    comment='One row per employee per month, carrying as-of-month state so no month-grain metric has to replay the event log. Both activity endpoints are stored so average headcount is exact.'
    )
    op.create_index('ix_snapshot_department_month', 'fact_monthly_headcount_snapshot', ['department_id', 'month_start'], unique=False)
    op.create_index('ix_snapshot_manager_month', 'fact_monthly_headcount_snapshot', ['manager_id', 'month_start'], unique=False)
    op.create_index('ix_snapshot_month', 'fact_monthly_headcount_snapshot', ['month_start'], unique=False)
    op.create_table('fact_performance_review',
    sa.Column('review_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('reviewer_id', sa.String(length=12), nullable=True),
    sa.Column('review_period_start', sa.Date(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False, comment='1-5'),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['dim_employee.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('review_id'),
    comment='Ratings 1-5. Regretted attrition needs the LAST rating before a voluntary exit; quality of hire needs the rating at day 180.'
    )
    op.create_index('ix_fact_review_employee_date', 'fact_performance_review', ['employee_id', 'review_date'], unique=False)
    op.create_table('fact_survey_response',
    sa.Column('response_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.SmallInteger(), nullable=False),
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('submitted_on', sa.Date(), nullable=False),
    sa.Column('enps_score', sa.SmallInteger(), nullable=False, comment='0-10. Promoters 9-10, passives 7-8, detractors 0-6.'),
    sa.Column('driver_manager', sa.SmallInteger(), nullable=False),
    sa.Column('driver_growth', sa.SmallInteger(), nullable=False),
    sa.Column('driver_recognition', sa.SmallInteger(), nullable=False),
    sa.Column('driver_workload', sa.SmallInteger(), nullable=False),
    sa.Column('driver_belonging', sa.SmallInteger(), nullable=False),
    sa.Column('open_text', sa.Text(), nullable=True, comment='Free-text comment. NULL when the respondent skipped it.'),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['dim_survey.survey_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id'),
    comment='One response per employee per survey. Participation rate is responses / eligible employees, where eligibility comes from the monthly headcount snapshot.'
    )
    op.create_index('ix_survey_response_employee', 'fact_survey_response', ['employee_id'], unique=False)
    op.create_index('ix_survey_response_survey_employee', 'fact_survey_response', ['survey_id', 'employee_id'], unique=True)
    op.create_table('fact_timesheet_week',
    sa.Column('timesheet_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('department_id', sa.SmallInteger(), nullable=False, comment='As-of-week department; also the team grain.'),
    sa.Column('week_start', sa.Date(), nullable=False, comment='Monday'),
    sa.Column('billable_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('non_billable_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('available_hours', sa.Numeric(precision=6, scale=2), nullable=False, comment='Capacity for the week; utilization denominator.'),
    sa.Column('output_units', sa.Numeric(precision=8, scale=2), nullable=True, comment='Tickets closed, story points, or deals.'),
    sa.Column('output_type', sa.Enum('tickets', 'story_points', 'deals', name='output_type'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['dim_department.department_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timesheet_id'),
    comment='One row per employee per week for billable departments. Hours are stored, never rates: overtime rate and utilization both divide at read time so the denominator stays visible.'
    )
    op.create_index('ix_timesheet_department_week', 'fact_timesheet_week', ['department_id', 'week_start'], unique=False)
    op.create_index('ix_timesheet_employee_week', 'fact_timesheet_week', ['employee_id', 'week_start'], unique=True)
    op.create_index('ix_timesheet_week', 'fact_timesheet_week', ['week_start'], unique=False)
    op.create_table('fact_training',
    sa.Column('training_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=12), nullable=False),
    sa.Column('course_code', sa.String(length=24), nullable=False),
    sa.Column('course_name', sa.String(length=96), nullable=False),
    sa.Column('assigned_on', sa.Date(), nullable=False),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=6, scale=2), nullable=False, comment='Hours spent; 0 if assigned but never started.'),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('training_id'),
    comment='One row per assigned course. completed_on is NULL while incomplete, which is what makes completion rate a count of non-nulls rather than a stored percentage.'
    )
    op.create_index('ix_fact_training_assigned', 'fact_training', ['assigned_on'], unique=False)
    op.create_index('ix_fact_training_employee', 'fact_training', ['employee_id'], unique=False)
    op.create_table('fact_application',
    sa.Column('application_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.String(length=12), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('candidate_ref', sa.String(length=16), nullable=False, comment='Synthetic candidate handle, e.g. C-004821.'),
    sa.Column('first_application_date', sa.Date(), nullable=False),
    sa.Column('final_stage', sa.Enum('applied', 'screen', 'interview', 'offer', 'hired', 'rejected', 'withdrawn', name='application_stage'), nullable=False),
    sa.Column('offer_extended_date', sa.Date(), nullable=True),
    sa.Column('offer_accepted_date', sa.Date(), nullable=True, comment='Ends both the time-to-fill and time-to-hire clocks.'),
    sa.Column('offer_declined_date', sa.Date(), nullable=True),
    sa.Column('rejected_date', sa.Date(), nullable=True),
    sa.Column('hired_employee_id', sa.String(length=12), nullable=True, comment='Links a hire back to its channel for quality of hire and cohort retention.'),
    sa.ForeignKeyConstraint(['hired_employee_id'], ['dim_employee.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requisition_id'], ['dim_requisition.requisition_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['dim_source.source_id'], ),
    sa.PrimaryKeyConstraint('application_id'),
    comment='~9,200 applications, one row per candidate per requisition. Time to hire = offer_accepted_date - first_application_date.'
    )
    op.create_index('ix_fact_application_first_date', 'fact_application', ['first_application_date'], unique=False)
    op.create_index('ix_fact_application_requisition', 'fact_application', ['requisition_id'], unique=False)
    op.create_index('ix_fact_application_source', 'fact_application', ['source_id'], unique=False)
    op.create_table('fact_comment_theme',
    sa.Column('comment_theme_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('survey_response_id', sa.BigInteger(), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', 'mixed', name='sentiment'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False, comment='0.000-1.000'),
    sa.Column('model', sa.String(length=48), nullable=False, comment='Model id that produced this, for auditability.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_response_id'], ['fact_survey_response.response_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_theme_id'),
    comment='Claude-extracted themes, written in phase 6 by a batch Haiku job. Cached here so the dashboard never blocks on a live API call, and so a failed call degrades to stale themes rather than an error.'
    )
    op.create_index('ix_comment_theme_response', 'fact_comment_theme', ['survey_response_id'], unique=False)
    op.create_index('ix_comment_theme_theme', 'fact_comment_theme', ['theme'], unique=False)
    op.create_table('fact_application_stage_event',
    sa.Column('stage_event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Enum('applied', 'screen', 'interview', 'offer', 'hired', 'rejected', 'withdrawn', name='application_stage'), nullable=False),
    sa.Column('entered_on', sa.Date(), nullable=False),
    sa.Column('exited_on', sa.Date(), nullable=True, comment='NULL = still in this stage.'),
    sa.ForeignKeyConstraint(['application_id'], ['fact_application.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stage_event_id'),
    comment='One row per application per stage entry. exited_on is NULL while the candidate sits in that stage, which is what makes the pipeline bottleneck measurable.'
    )
    op.create_index('ix_fact_stage_event_application', 'fact_application_stage_event', ['application_id'], unique=False)
    op.create_index('ix_fact_stage_event_stage_entered', 'fact_application_stage_event', ['stage', 'entered_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_stage_event_stage_entered', table_name='fact_application_stage_event')
    op.drop_index('ix_fact_stage_event_application', table_name='fact_application_stage_event')
    op.drop_table('fact_application_stage_event')
    op.drop_index('ix_comment_theme_theme', table_name='fact_comment_theme')
    op.drop_index('ix_comment_theme_response', table_name='fact_comment_theme')
    op.drop_table('fact_comment_theme')
    op.drop_index('ix_fact_application_source', table_name='fact_application')
    op.drop_index('ix_fact_application_requisition', table_name='fact_application')
    op.drop_index('ix_fact_application_first_date', table_name='fact_application')
    op.drop_table('fact_application')
    op.drop_index('ix_fact_training_employee', table_name='fact_training')
    op.drop_index('ix_fact_training_assigned', table_name='fact_training')
    op.drop_table('fact_training')
    op.drop_index('ix_timesheet_week', table_name='fact_timesheet_week')
    op.drop_index('ix_timesheet_employee_week', table_name='fact_timesheet_week')
    op.drop_index('ix_timesheet_department_week', table_name='fact_timesheet_week')
    op.drop_table('fact_timesheet_week')
    op.drop_index('ix_survey_response_survey_employee', table_name='fact_survey_response')
    op.drop_index('ix_survey_response_employee', table_name='fact_survey_response')
    op.drop_table('fact_survey_response')
    op.drop_index('ix_fact_review_employee_date', table_name='fact_performance_review')
    op.drop_table('fact_performance_review')
    op.drop_index('ix_snapshot_month', table_name='fact_monthly_headcount_snapshot')
    op.drop_index('ix_snapshot_manager_month', table_name='fact_monthly_headcount_snapshot')
    op.drop_index('ix_snapshot_department_month', table_name='fact_monthly_headcount_snapshot')
    op.drop_table('fact_monthly_headcount_snapshot')
    op.drop_index('ix_fact_goal_employee_quarter', table_name='fact_goal')
    op.drop_index('ix_fact_goal_department_quarter', table_name='fact_goal')
    op.drop_table('fact_goal')
    op.drop_index('ix_flight_risk_month_score', table_name='fact_flight_risk_score')
    op.drop_table('fact_flight_risk_score')
    op.drop_index('ix_fact_employment_event_type_date', table_name='fact_employment_event')
    op.drop_index('ix_fact_employment_event_employee_date', table_name='fact_employment_event')
    op.drop_table('fact_employment_event')
    op.drop_index('ix_fact_absence_employee_date', table_name='fact_absence')
    op.drop_table('fact_absence')
    op.drop_index('ix_dim_requisition_status_opened', table_name='dim_requisition')
    op.drop_index('ix_dim_requisition_department', table_name='dim_requisition')
    op.drop_table('dim_requisition')
    op.drop_table('fact_department_revenue')
    op.drop_index('ix_dim_employee_termination_date', table_name='dim_employee')
    op.drop_index('ix_dim_employee_manager', table_name='dim_employee')
    op.drop_index('ix_dim_employee_hire_date', table_name='dim_employee')
    op.drop_index('ix_dim_employee_department', table_name='dim_employee')
    op.drop_table('dim_employee')
    op.drop_table('dim_survey')
    op.drop_table('dim_source')
    op.drop_table('dim_location')
    op.drop_table('dim_job_level')
    op.drop_table('dim_department')
    op.drop_index('ix_dim_date_week_start', table_name='dim_date')
    op.drop_index('ix_dim_date_quarter_start', table_name='dim_date')
    op.drop_index('ix_dim_date_month_start', table_name='dim_date')
    op.drop_table('dim_date')
    # ### end Alembic commands ###

    # Hand-added: drop the native enum types the autogenerated block leaves behind.
    # Tables are gone by this point, so nothing depends on them.
    for enum_name in ENUM_TYPE_NAMES:
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
